Repository stone-payments/emerald-web-framework, pull requests merged in 2018-10, with the labels that each got.

#78 [MASTER] Release/1.8.0
  CHANGELOG.md
  lerna.json
  package-lock.json
  package.json
  packages/sling-assets/package.json
  packages/sling-framework/package.json
  packages/sling-framework/src/index.js
  packages/sling-framework/src/v1/src/index.js
  packages/sling-helpers/package.json
  packages/sling-web-component-brand-icon/package.json
  packages/sling-web-component-button/package.json
  packages/sling-web-component-calendar/package.json
  packages/sling-web-component-card/package.json
  packages/sling-web-component-form/package.json
  packages/sling-web-component-icon/package.json
  packages/sling-web-component-input/package.json
  packages/sling-web-component-list/package.json
  packages/sling-web-component-loader-wrapper/package.json
  packages/sling-web-component-loader/package.json
  packages/sling-web-component-login/package.json
  packages/sling-web-component-message/package.json
  packages/sling-web-component-paginator/package.json
  packages/sling-web-component-sdk-connect/package.json
  packages/sling-web-component-select/package.json
  packages/sling-web-component-snackbar/package.json
  packages/sling-web-component-table/package.json
Labels: release

#79 [DEVELOP] Release/1.8.0
  CHANGELOG.md
  lerna.json
  package-lock.json
  package.json
  packages/sling-assets/package.json
  packages/sling-framework/package.json
  packages/sling-helpers/package.json
  packages/sling-web-component-brand-icon/package.json
  packages/sling-web-component-button/package.json
  packages/sling-web-component-calendar/package.json
  packages/sling-web-component-card/package.json
  packages/sling-web-component-form/package.json
  packages/sling-web-component-icon/package.json
  packages/sling-web-component-input/package.json
  packages/sling-web-component-list/package.json
  packages/sling-web-component-loader-wrapper/package.json
  packages/sling-web-component-loader/package.json
  packages/sling-web-component-login/package.json
  packages/sling-web-component-message/package.json
  packages/sling-web-component-paginator/package.json
  packages/sling-web-component-sdk-connect/package.json
  packages/sling-web-component-select/package.json
  packages/sling-web-component-snackbar/package.json
  packages/sling-web-component-table/package.json
Labels: release

#89 Remove makeRequest helper from domHelper close Issue #88
  package-lock.json
  packages/sling-helpers/src/dom/domHelper.js
  packages/sling-helpers/src/dom/makeRequest.js
  packages/sling-helpers/src/dom/makeRequest.test.js
Labels: enhancement

#94 fix: Export makeRequest method
  packages/sling-helpers/src/dom/domHelper.js
Labels: bug
